const lessonLibrary = {
  1: {
    title: "Meet Your Machine", time: "10 minutes", supplies: "Your machine and its manual",
    intro: "Learn the parts and controls you will use in nearly every sewing project, then locate each one on your own machine.",
    steps: [
      ["START WITH YOUR MODEL","Find your manual","Turn the machine off and find the manual for your exact make and model. A printed or digital copy is fine. Keep it nearby because button locations and symbols vary.","Manual","Search the manufacturer’s website using the full model number.","Your manual always takes priority over general instructions."],
      ["THREAD SUPPLY","Locate the spool pin and bobbin-winding area","Find the spool pin, first thread guide, bobbin-winding tension guide, bobbin-winder spindle, and bobbin-winder stopper.","Spool","These parts are usually across the top of the machine.","The sewing path and bobbin-winding path are separate."],
      ["UPPER THREAD PATH","Find the tension area and take-up lever","Follow the printed threading arrows from the spool toward the needle. Identify the thread channels, tension area, and moving take-up lever.","Path","Turn the handwheel toward you to watch the take-up lever move.","You will use this path in Lesson 5."],
      ["NEEDLE AREA","Identify the working parts","Locate the needle, needle-clamp screw, presser foot, presser-foot lever, needle plate, feed dogs, and bobbin cover or bobbin case.","Needle","Keep the machine off while your fingers are near the needle.","The feed dogs move fabric; you guide it rather than push it."],
      ["MAIN CONTROLS","Find the controls you will use most","Locate the power switch, handwheel, reverse control, stitch selector, stitch length and width controls, speed control if present, and start/stop button if your machine has one.","Controls","Button symbols differ, so compare them with your manual.","Always turn the handwheel toward you unless your manual says otherwise."],
      ["PRACTICAL CHECK","Point to each part on your machine","Without looking at this page, locate the spool pin, handwheel, reverse control, presser-foot lever, needle, presser foot, feed dogs, bobbin area, and power switch.","Ready","If you can find them, you are ready for the next lesson.","You do not need to memorize every decorative stitch or specialty button yet."]
    ],
    trouble: [["I cannot find my manual","Search the manufacturer’s support website using the complete model number printed on the machine."],["My controls look different","That is normal. Match the function names here with the diagrams and symbols in your manual."],["I cannot see the take-up lever","Turn the handwheel toward you until the needle and take-up lever rise."]]
  },
  2: {
    title: "Prepare to Sew", time: "8–12 minutes", supplies: "Machine, manual, needle, foot pedal and power cord",
    intro: "Set up a safe, comfortable workspace and check the parts that need to be ready before you add thread.",
    steps: [
      ["SET UP YOUR SPACE","Choose a stable work surface","Place the machine on a sturdy table with enough room for fabric to rest without pulling. Sit where your shoulders can relax and you can look directly at the needle area.","Table","Support the machine and the fabric on the table.","Good lighting makes threading and needle checks much easier."],
      ["CONNECT SAFELY","Attach the power cord and foot pedal","With the power switch off, connect the power cord and foot pedal firmly. Place the pedal where your foot can rest naturally without reaching.","Power","Keep cords away from walkways and the machine’s moving parts.","Do not turn the machine on yet."],
      ["CHECK THE NEEDLE","Inspect the installed needle","Look for bending, dullness, burrs, or damage. Confirm that the needle is pushed fully upward and that its flat side faces the direction specified in your manual.","Needle","When in doubt, install a new universal needle appropriate for your fabric.","Keep the machine off while working near the needle."],
      ["CHECK THE FOOT","Identify and lower the presser foot","Confirm that a standard presser foot is securely attached. Practice raising and lowering it with the presser-foot lever.","Foot","The foot must be lowered before sewing.","The machine may look ready while the foot is still raised, so check every time."],
      ["CLEAR THE AREA","Remove lint and loose objects","Brush visible lint from the needle plate and bobbin area with the machine off. Remove pins, scraps, and tools from around the handwheel and needle.","Clear","Use a small brush rather than blowing lint farther inside.","Only oil the machine if your manual specifically instructs you to."],
      ["READINESS CHECK","Test the controls without thread","Turn the machine on. Confirm the light works and gently press the pedal for a moment while keeping your hands away from the needle. Turn it off again.","Ready","The needle should move smoothly without unusual grinding or knocking.","If it sounds wrong, stop and check the troubleshooting guide before continuing."]
    ],
    trouble: [["The machine does not turn on","Check the outlet, power switch, and both ends of the power cord. Some plugs require a firm push."],["The pedal does nothing","Confirm it is connected to the correct port and the machine is switched on."],["The needle looks bent","Do not sew with it. Replace it with the correct type and size."]]
  },
  3: {
    title: "Wind a Bobbin", time: "10 minutes", supplies: "Machine, correct empty bobbin and all-purpose thread",
    intro: "Wind a smooth, evenly filled bobbin that can feed consistently while you sew.",
    steps: [
      ["USE THE RIGHT PART","Choose the correct bobbin","Use only the bobbin type specified for your machine. Bobbins that look similar can differ in height, curve, or width and may cause poor stitches or damage.","Bobbin","Compare the bobbin with the diagram or part number in your manual.","Do not wind over old thread; begin with an empty bobbin."],
      ["SET UP THE THREAD","Place the spool on its pin","Install the thread and spool cap as directed by your manual. The spool should turn freely without wobbling or catching.","Spool","Use smooth, good-quality thread.","Old or fuzzy thread can wind unevenly."],
      ["FOLLOW THE WINDING PATH","Use the bobbin-winding tension guide","Follow the bobbin-winding arrows, which are usually different from the upper-threading path. Wrap the thread firmly around the winding tension disc as shown on your machine.","Guide","Hold light tension while seating the thread.","Missing this guide creates a loose, spongy bobbin."],
      ["ATTACH THE BOBBIN","Thread the bobbin and place it on the spindle","Pass the thread through the bobbin hole from the inside to the outside if your manual directs. Push the bobbin fully onto the winder spindle.","Attach","Hold the thread tail upward.","Some machines secure the thread in a cutter instead of using the hole."],
      ["ENGAGE THE WINDER","Move the spindle into winding position","Push or move the bobbin-winder spindle in the direction shown on your machine. A screen symbol or mechanical click may confirm winding mode.","Engage","The needle may stop moving while the winder is engaged.","Never force a spindle that does not move easily."],
      ["BEGIN WINDING","Wind a few layers and trim the tail","Turn the machine on. Hold the thread tail and press the pedal or start button slowly. Stop after several wraps, trim the tail close to the bobbin, then continue.","Wind","Keep fingers away from the spinning bobbin.","Stop if thread begins collecting under the bobbin."],
      ["FINISH AND INSPECT","Stop when the bobbin is evenly filled","Allow the machine to stop automatically or stop before thread extends beyond the rim. Cut the thread, disengage the winder, and remove the bobbin.","Check","The thread should look firm, smooth, and level across the bobbin.","Rewind a soft, lopsided, or overfilled bobbin before sewing."]
    ],
    trouble: [["The bobbin winds loosely","Rethread the bobbin-winding tension guide and hold gentle tension as winding begins."],["Thread collects under the bobbin","Stop, remove the bobbin, clear the tangled thread, and restart with the bobbin fully seated."],["The needle moves while winding","Some machines do this normally. Check the manual before adjusting the handwheel or clutch."],["The bobbin is lopsided","Confirm the bobbin is pushed fully onto the spindle and the winding guide is threaded correctly."]]
  },
  4: {
    title: "Insert Your Bobbin", time: "10 minutes", supplies: "Machine and a correctly wound bobbin",
    intro: "Identify your bobbin system and install the bobbin so the lower thread feeds in the correct direction and under the correct tension.",
    steps: [
      ["IDENTIFY YOUR SYSTEM","Top-loading or front-loading?","A top-loading bobbin drops into a compartment beneath a clear or removable cover. A front-loading bobbin sits inside a removable metal or plastic case behind the accessory tray.","Choose","Compare your machine with its manual before continuing.","The two systems use different insertion methods."],
      ["PREPARE THE MACHINE","Raise the needle and presser foot","Turn the machine off. Turn the handwheel toward you until the needle is at its highest position, then raise the presser foot and open the bobbin area.","Raise","Keep fingers away from the needle.","Remove lint you can reach with a small brush."],
      ["TOP-LOADING PATH","Drop the bobbin into place","For a top-loading system, place the bobbin into the holder with the thread unwinding in the direction shown on the cover or in the manual—often counterclockwise, but not always.","Top load","Keep one finger lightly on the bobbin.","Do not assume the direction; use your machine’s diagram."],
      ["TOP-LOADING TENSION","Pull thread through the slot","Guide the thread into the first slot, around the marked path, and under the tension spring. Pull it into the cutter if your machine has one, then replace the cover.","Slot","You should feel slight resistance after the thread enters the tension path.","A bobbin simply dropped in without using the slot is not fully inserted."],
      ["FRONT-LOADING CASE","Load the removable bobbin case","For a front-loading system, place the bobbin into its case in the direction shown in the manual. Pull the thread through the case slot and underneath the flat tension spring.","Case","Leave several inches of thread extending from the case.","The thread should pull smoothly with light resistance."],
      ["FRONT-LOADING INSTALLATION","Insert the case into the machine","Hold the case by its latch, align its finger or notch with the hook assembly, and push it into place until fully seated. Release the latch and replace the accessory tray or cover.","Insert","The case should not fall out when properly installed.","Never force the case; recheck its alignment."],
      ["CHECK THE RESULT","Test the lower thread","Gently pull the bobbin thread. It should feed smoothly with slight, consistent resistance and without the bobbin jumping out of position.","Check","If it feels stuck or completely loose, remove and reinstall it.","Your bobbin is now ready for the upper thread and test stitch lessons."]
    ],
    trouble: [["The bobbin jumps or spins freely","Remove it and confirm the thread follows the slot and tension path shown on the machine."],["The thread will not pull","Check for tangles, confirm the bobbin is facing the correct direction, and reinstall it."],["The front-loading case will not stay in","Hold the latch while inserting and align the case finger with the hook notch."],["I am unsure which system I have","Top-loading bobbins are placed flat from above; front-loading bobbins go into a separate removable case."]]
  }
};

const lessonId = Number(document.body.dataset.lessonId);
const lesson = lessonLibrary[lessonId];
const app = document.querySelector('#lesson-app');
const stepMarkup = lesson.steps.map((s,i)=>`<article class="lesson-step${i===0?' active':''}" data-step="${i+1}"><div class="step-number">${String(i+1).padStart(2,'0')}</div><div class="step-copy"><p class="small-label">${s[0]}</p><h2>${s[1]}</h2><p>${s[2]}</p><aside class="sage-tip"><strong>Sage’s Tip</strong><p>${s[4]}</p></aside><aside class="common-mistake"><strong>Remember</strong><p>${s[5]}</p></aside>${i===lesson.steps.length-1?`<div class="finish-actions"><button type="button" id="complete-lesson" class="button button-primary">Complete Lesson ${lessonId}</button></div>`:''}</div><div class="step-visual"><span class="visual-symbol">${i+1}</span><strong>${s[3]}</strong><p>Check this on your own machine</p></div></article>`).join('');
const troubleMarkup = lesson.trouble.map(t=>`<details><summary>${t[0]}</summary><p>${t[1]}</p></details>`).join('');

app.innerHTML=`<header class="site-header"><a class="brand" href="index.html"><span class="brand-leaf">S</span><span><strong>Sage's Sewing Studio</strong><small>by The Sage Garden</small></span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="site-nav">☰<span class="sr-only">Open navigation</span></button><nav id="site-nav" class="site-nav"><a href="course.html">Learn</a><a href="index.html#projects">Projects</a><a href="index.html#help">Machine Help</a><a href="index.html#downloads">Downloads</a><a href="index.html#patterns">Pattern Shop</a><a class="nav-about" href="index.html#about">About Sage</a></nav></header><main><section class="lesson-heading"><div><a class="back-link" href="course.html">← Back to Sewing 101</a><p class="eyebrow"><span></span> Lesson ${String(lessonId).padStart(2,'0')} of 13</p><h1>${lesson.title}</h1><p class="large-copy">${lesson.intro}</p></div><dl class="lesson-facts"><div><dt>Time</dt><dd>${lesson.time}</dd></div><div><dt>Level</dt><dd>Complete beginner</dd></div><div><dt>You’ll need</dt><dd>${lesson.supplies}</dd></div></dl></section><div class="lesson-toolbar"><div class="view-toggle"><button class="view-button active" type="button" data-view="guided">Guided Mode</button><button class="view-button" type="button" data-view="full">Full Lesson</button></div><button class="print-button" type="button" id="print-lesson">Print lesson</button><a class="trouble-button" href="#troubleshooting">Having issues?</a></div><section class="lesson-progress-wrap"><span id="step-label">Step 1 of ${lesson.steps.length}</span><div class="lesson-progress"><span id="lesson-progress-fill"></span></div></section><section class="lesson-content" id="lesson-content">${stepMarkup}</section><nav class="step-navigation"><button type="button" id="previous-step">← Previous</button><button type="button" id="next-step">Next step →</button></nav><section id="troubleshooting" class="lesson-troubleshooting"><p class="eyebrow light-eyebrow"><span></span> Having issues?</p><h2>Start with what you are seeing.</h2><div class="trouble-grid">${troubleMarkup}</div><a class="button trouble-light-button" href="index.html#help">Open the full troubleshooting guide →</a></section></main><footer class="site-footer"><div><strong>Sage's Sewing Studio</strong><span>by The Sage Garden</span></div><p>Beginner-friendly sewing lessons, projects, and patterns.</p><p>© <span id="year"></span> The Sage Garden</p></footer>`;
